#  错误处理及测试
================

不像其他主流语言的try/catch机制 go使用defer-panic-and-recover机制来处理异常。go 语言设计者认为try/catch那种从底层抛异常到高层会浪费太多的资源

go处理常规的错误方法是：对于方法或者函数 让其返回一个错误对象作为其唯一或者最后一个返回值（或者nil当没有错误发生时）， 对于方法调用者总是需要检测其受到的返回值是否存在错误！
！！！永远不要忽略错误，忽略错误会导致程序崩溃的.
[[上面的策略其实可以用于任何通信系统  在协议设计时比如rpc调用时 总是搞一个error字段]]

panic-and-recover 用来处理真正的异常（不可预料的）而不是用来处理常规的错误。
一些惯用法： 
-	可能导致错误的方法会返回两个变量，一个value和一个error-code; 后者是nil时表示成功调用，但不为nil时 表示错误发生。
-	在方法调用后 错误被检查 ， 如果error!= nil 正常的方法执行会终止（甚至是整个程序）。

~~~
if value, err := pack1.Func1(param1); err != nil {
fmt.Printf(“Error %s in pack1.Func1 with parameter %v”, err.Error(), param1)
	return // or: return err
}
// Process(value)
~~~
>   在复合型if语句中 总是把错误赋给一个变量  让代码更易读。

## 错误处理
-----
go的预定义错误接口类型

~~~
type error interface {
Error() string
}
~~~
errors包中有个errorString 结构实现了error接口 。可以使用os.Exit(1)来在错误发生时停止程序的执行。

### 定义错误
----
err := errors.New("math - square root of negative number")

var errNotFound error = errors.New(“Not found error”)

方法中返回：
~~~
func Sqrt(f float64) (float64, error) {
	if f < 0 {
		return 0, errors.New (“math - square root of negative number”)
	}
	// implementation of Sqrt
}
// 可以这样使用
if f, err := Sqrt(-1); err != nil {
	fmt.Printf(“Error: %s\n”, err)
}
~~~
自定义错误 ， 会引入更多信息：

~~~
// PathError records an error and the operation and file path that caused it.
type PathError struct {
	Op string // “open”, “unlink”, etc.
	Path string // The associated file.
	Err error // Returned by the system call.
}
func (e *PathError) String() string {
	return e.Op + “ ” + e.Path + “: “+ e.Err.Error()
}

// 根据不同的错误类型执行不同的操作：
// err != nil
if e, ok := err.(*os.PathError); ok {
	// remedy situation
}
//Or:
switch err := err.(type) {
	case ParseError:
		PrintParseError(err)
	case PathError:
		PrintPathError(err)
		…
	default:
		fmt.Printf(“Not a special error, just %s\n”, err)
}
~~~
不同的包里面可能有自己的错误类型。调用者可能需要使用异常断言功能：
if serr, ok := err.(*json.SyntaxError); ok {
	line, col := findLine(f, serr.Offset)
	return fmt.Errorf(“%s:%d:%d: %v”, f.Name(), line, col, err)
}
可以定义自己的错误接口：
package net
type Error interface {
	Timeout() bool // Is the error a timeout?
	Temporary() bool // Is the error temporary?
}

系统调用比较底层 syscall.Errno实现了Error 接口。许多系统调用返回一个结果和一个可能的错误：

~~~
r, err := syscall.Open(name, mode, perm)
if err != 0 {
	fmt.Println(err.Error())
}
~~~

